---
- hosts: all
  become: false
  no_log: false
  gather_facts: no
  pre_tasks:
  - name: Verifying ansible_limit
    assert:
      that: ansible_limit != ""
      fail_msg: "'limit' should not be blank"
      success_msg: "'limit' is {{ ansible_limit }}"

  tasks:
  - name: Include variables of users into the 'users' variable.
    include_vars:
      file: "{{ team }}.yml"
  - name: password expiration
    user:
      shell: chage -m 0 -M 99999 -I -1 -E -1 {{ item.username }}
    with_items: "{{ users }}"
    become: yes